// <auto-generated />
namespace TimeClock.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pinIsNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pinIsNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201606200247405_pinIsNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
